@isTest
public class TestAccount {
    /*
	static MockDAO.AccountDAOMock contactDAOMockInstance = new MockDAO.AccountDAOMock();
    Account contObj = TestDataFactory.createAccount(true,accObj.id);
    @isTest
    private static void generateAccountTest() {
        
        List<Account> Accounts = new List<Account>();
        //List<Contact> upContacts = new List<Contact>();
        Account acc = new Account(FirstName = 'John', LastName = 'Doe');
        
        contactDAOMockInstance.accList = Accounts;
        
        //List<Contact> returnedAccounts = new List<Account>();
        Test.startTest();
        Database.SaveResult[] srList = AccountDemoClass.demoMethod(contacts);
        Test.stopTest();
}
 */
}