public with sharing class WorkingWithSOQL {
    public static void WorkingWithSOQL() {
        insert new Account(Name='Singha');
        Account acc = [SELECT Id FROM Account WHERE Name='Singha' LIMIT 1];
        //Account acc1 = [SELECT Id FROM Account WHERE Name='Singha' LIMIT 1].Name; --> Gives Run Time error
        System.debug('ID : ' + acc);
        //System.debug(acc1); --> Gives Run Time error

        String name  = [SELECT Id, Name FROM Account WHERE Name='Singha' LIMIT 1].Name;
        System.debug('Name:' + name);
    }
}